stages:
  - build
  - unit-test

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm install


unit-test:
  stage: unit-test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
