workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

variables:
  IMAGE_NODE: node:14-alpine

stages:
  - clean
  - build
  - test
  - build-image
  - publish-image
  - deploy

clean:
  image: $IMAGE_NODE
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - apk update && apk add git
    - git clean -xdf

build:
  image: $IMAGE_NODE
  stage: build
  script:
    - echo "Building React..."
    - npm install
  artifacts:
    paths:
      - node_modules/

static-code-analysis:
  image: $IMAGE_NODE
  stage: test
  script:
    - echo "Running Static Code Analysis..."
    - npm run lint

unit-test:
  image: $IMAGE_NODE
  stage: test
  script:
    - echo "Running unit tests..."
    - npm run test

coverage-test:
  image: $IMAGE_NODE
  stage: test
  needs:
    - job: unit-test
  script:
    - echo "Running coverage tests..."

build-image:
  stage: build-image
  script:
    - echo "Building Docker Image..."
    - docker build -t $CI_REGISTRY/qryptic/qryptic-web:$CI_COMMIT_SHORT_SHA .
    - docker build -t $CI_REGISTRY/qryptic/qryptic-web:latest .

publish-image:
  stage: publish-image
  script:
    - echo "Publishing Docker Image..."
    - docker login -u mjovanc -p $QRYPTIC_CONTAINER_REGISTRY_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/qryptic/qryptic-web:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/qryptic/qryptic-web:latest

deploy:
  stage: deploy
  trigger: qryptic/qryptic-iac